// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AngularVSExtension
{
    static class Vsix
    {
        public const string Id = "593771d0-13b5-4de6-a192-165dd6f16144";
        public const string Name = "Angular Html TS Switcher";
        public const string Description = @"Easily navigate between typescript(.ts) and template(.html) in angular project and ng serve angular project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Osama Abu-Sitta";
        public const string Tags = "angular, typescript, web, html, ts";
    }
}
