// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AngularVSExtension2022
{
    internal sealed partial class Vsix
    {
        public const string Id = "05D8FE2B-55EC-4A28-8865-C2570F30A1C9";
        public const string Name = "Angular Html TS Switcher";
        public const string Description = @"Easily navigate between typescript(.ts) and template(.html) in angular project and ng serve angular project.";
        public const string Language = "en-US";
        public const string Version = "2.2";
        public const string Author = "Osama Abu-Sitta";
        public const string Tags = "angular, typescript, web, html, ts";
    }
}
