// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AngularVSExtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidTypeScriptHtmlSwitchCommandPackageString = "14261379-f70d-4d2a-b69f-653605fb158f";
        public static Guid guidTypeScriptHtmlSwitchCommandPackage = new Guid(guidTypeScriptHtmlSwitchCommandPackageString);

        public const string guidTypeScriptHtmlSwitchCommandPackageCmdSetString = "fde67d78-b48b-4d07-9643-af7a2e1cab14";
        public static Guid guidTypeScriptHtmlSwitchCommandPackageCmdSet = new Guid(guidTypeScriptHtmlSwitchCommandPackageCmdSetString);

        public const string HTMLContextString = "78f03954-2fb8-4087-8ce7-59d71710b3bb";
        public static Guid HTMLContext = new Guid(HTMLContextString);

        public const string guidTypeScriptHtmlSwitchCommandPackageCmdSet2String = "61323670-1806-43d2-8482-b0a3ed4d1c8b";
        public static Guid guidTypeScriptHtmlSwitchCommandPackageCmdSet2 = new Guid(guidTypeScriptHtmlSwitchCommandPackageCmdSet2String);

        public const string guidTypeScriptHtmlSwitchCommandPackageCmdSet1String = "953f9758-2fbb-4e2c-abad-e8bac60fed4b";
        public static Guid guidTypeScriptHtmlSwitchCommandPackageCmdSet1 = new Guid(guidTypeScriptHtmlSwitchCommandPackageCmdSet1String);

        public const string guidSwitchSourceOrTargetImgString = "476e20e3-e034-4e61-93eb-6de3d19ce043";
        public static Guid guidSwitchSourceOrTargetImg = new Guid(guidSwitchSourceOrTargetImgString);

        public const string guidAngularImgString = "476e20e3-e034-4e11-93eb-6de3d19ce143";
        public static Guid guidAngularImg = new Guid(guidAngularImgString);

        public const string guidCommandImgString = "2fe884c3-861b-4317-9246-25d351d8c93d";
        public static Guid guidCommandImg = new Guid(guidCommandImgString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup1 = 0x1020;
        public const int TypeScriptHtmlSwitchCommandId = 0x0100;
        public const int menu = 0x0001;
        public const int MyMenuGroup2 = 0x1020;
        public const int cmdidOpenInCmdCommand = 0x0100;
        public const int cmdidNgServeCommand = 0x0100;
        public const int MyMenuGroup3 = 0x1020;
        public const int TopLevelMenu = 0x1021;
        public const int guidSwitchSourceOrTargetImgPic = 0x0001;
        public const int guidAngularImgPic = 0x0001;
        public const int guidCommandImgPic = 0x0001;
    }
}